name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint (SAST)
      run: npm run sast

    - name: Run tests (smoke)
      run: npm run test

    - name: NPM audit (SCA)
      run: |
        npm audit --json > npm-audit-report.json || true

    - name: OWASP Dependency-Check (SCA)
      uses: dependency-check/Dependency-Check_Action@main
      id: depcheck
      with:
        project: 'lab1-security-scan'
        path: '.'
        format: 'ALL'
        args: >
          --enableRetired
          --enableExperimental
          --out reports

    - name: Upload OWASP Dependency-Check reports
      uses: actions/upload-artifact@v4
      with:
        name: owasp-dependency-check-reports
        path: reports/

    - name: Upload NPM audit report
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-report
        path: npm-audit-report.json

    - name: Show audit summaries
      run: |
        echo "=== NPM Audit Summary ==="
        if [ -f npm-audit-report.json ]; then 
          jq '.metadata.vulnerabilities' npm-audit-report.json || true
        else 
          echo "No NPM audit report"
        fi
        echo ""
        echo "=== OWASP Dependency-Check Summary ==="
        if [ -f reports/dependency-check-report.json ]; then
          echo "OWASP scan completed. Check artifacts for detailed report."
          jq '.dependencies | length' reports/dependency-check-report.json || true
        else
          echo "No OWASP report found"
        fi

    - name: Fail on critical vulnerabilities
      run: |
        FAIL=0
        if [ -f npm-audit-report.json ]; then 
          CV=$(jq '.metadata.vulnerabilities.critical // 0' npm-audit-report.json)
          if [ "$CV" -gt 0 ]; then 
            echo "NPM Audit: $CV critical vulnerabilities found"
            FAIL=1
          fi
        fi
        
        if [ -f reports/dependency-check-report.json ]; then
          HIGH_CRITICAL=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity == "HIGH" or .severity == "CRITICAL")] | length' reports/dependency-check-report.json || echo "0")
          if [ "$HIGH_CRITICAL" -gt 0 ]; then
            echo "OWASP Dependency-Check: $HIGH_CRITICAL high/critical vulnerabilities found"
            FAIL=1
          fi
        fi
        
        if [ "$FAIL" -eq 1 ]; then
          echo "Security scan failed due to critical vulnerabilities"
          exit 1
        else
          echo "No critical vulnerabilities found"
        fi
